# This script deploys your website automatically
name: CI

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [ main ]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
    - uses: actions/checkout@v4

    - run: |
       git config --global user.email "nate0023@gmail.com"
       git config --global user.name "Nathan Watkins"

    - name: Install
      run: npm install

    # Run our deployment command
    - name: Deploying the static website to gh-pages
      run: npm run deploy
      env:
         CI: ""
